enum EmployeeActionTypes {
    GET_EMPLOYEES = 'GET_EMPLOYEES',
    GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS',
    GET_EMPLOYEES_FAIL = 'GET_EMPLOYEES_FAIL',
    ADD_EMPLOYEE = 'ADD_EMPLOYEE',
    ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS',
    ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL',
    EDIT_EMPLOYEE = 'EDIT_EMPLOYEE',
    EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS',
    EDIT_EMPLOYEE_FAIL = 'EDIT_EMPLOYEE_FAIL',
    DELETE_EMPLOYEE = 'DELETE_EMPLOYEE',
    DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL',
    RESET_EMPLOYEES = 'RESET_EMPLOYEES'
}

export default EmployeeActionTypes;