enum ProjectActionTypes {
    GET_PROJECTS = 'GET_PROJECTS',
    GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS',
    GET_PROJECTS_FAIL = 'GET_PROJECTS_SUCCESS',
    ADD_PROJECT = 'ADD_PROJECT',
    ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS',
    ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL',
    START_PROJECT = 'START_PROJECT',
    START_PROJECT_SUCCESS = 'START_PROJECT_SUCCESS',
    START_PROJECT_FAIL = 'START_PROJECT_FAIL',
    COMPLETE_PROJECT = 'COMPLETE_PROJECT',
    COMPLETE_PROJECT_SUCCESS = 'COMPLETE_PROJECT_SUCCESS',
    COMPLETE_PROJECT_FAIL = 'COMPLETE_PROJECT_FAIL',
    DELETE_PROJECT = 'DELETE_PROJECT',
    DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',
    DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL',
    SET_SELECTED_STATUS = 'SET_SELECTED_STATUS',
    FILTER_PROJECTS_BY_STATUS = 'FILTER_PROJECTS_BY_STATUS',
    RESET_PROJECTS = 'RESET_PROJECTS'
}

export default ProjectActionTypes;