enum DashboardActionTypes {
    GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA',
    GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS',
    GET_DASHBOARD_DATA_FAIL = 'GET_DASHBOARD_DATA_FAIL',
    RESET_DASHBOARD = 'RESET_DASHBOARD'
}

export default DashboardActionTypes;